# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""L4/L5 golden parity tests for the HuggingFace Nemotron 3 Diarization model.

Builds both ONNX diarization graphs (offline ``DiarizationTask`` and
streaming ``DiarizationStreamingTask``) from the real
``nvidia/Nemotron-3-Diarization`` checkpoint via the generic
:func:`mobius.build` pipeline and compares their output against pre-computed
HuggingFace references
(``testdata/golden/speech/nemotron3_diarization.npz``).

The reference was generated by running the real HuggingFace
``Nemotron3DiarizationForAudioFrameClassification`` reference implementation —
regenerate it with ``scripts/generate_nemotron3_diarization_golden.py`` if the
architecture changes. (``nemotron3_diarization``'s task strings,
``diarization``/``diarization-streaming``, are not part of the generic
``testdata/cases/`` + ``scripts/generate_golden.py`` YAML pipeline — see
``tests/model_coverage_test.py``'s ``_COVERAGE_SKIP`` entry for this model,
same as ``sortformer``.)

- **L4** (``test_offline_diarization_parity``): the ONNX offline
  ``speaker_probs`` match the HuggingFace single-pass reference element-wise,
  for an input short enough that HuggingFace's own offline forward does not
  internally re-chunk (matching the regime the mobius offline graph is
  documented to reproduce bit-for-bit).
- **L5** (``test_streaming_diarization_session``): a 3-chunk streaming
  session — replaying the Arrival-Order Speaker Cache (AOSC) + FIFO queue
  state through the *real* exported ONNX graph, chunk by chunk — reproduces
  HuggingFace's per-chunk speaker probabilities *and* cache state (embeddings,
  probabilities, FIFO, occupancy counters, compression flag) exactly. With
  this checkpoint's streaming config (FIFO capacity 264, cache capacity 264,
  update period 222), a single default-sized chunk (340 encoder frames)
  already overflows the FIFO, so by the second chunk this also exercises the
  top-k AOSC compression path.
"""

from __future__ import annotations

import json
import os
import tempfile

import numpy as np
import onnx_ir as ir
import onnxruntime as ort
import pytest

pytestmark = pytest.mark.integration

_MODEL_ID = "nvidia/Nemotron-3-Diarization"
# Pin the HF revision so the test always validates against the exact model the
# committed golden was generated from (see
# scripts/generate_nemotron3_diarization_golden.py).
_REVISION = "f667ed73aee57d40cc39428eb768b4fd87a0a29e"
_GOLDEN = os.path.join(
    os.path.dirname(__file__),
    "..",
    "testdata",
    "golden",
    "speech",
    "nemotron3_diarization.npz",
)


def _run_onnx(pkg, feed: dict[str, np.ndarray]) -> dict[str, np.ndarray]:
    with tempfile.TemporaryDirectory() as td:
        path = os.path.join(td, "model.onnx")
        ir.save(pkg["model"], path, external_data="model.onnx.data")
        sess = ort.InferenceSession(path, providers=["CPUExecutionProvider"])
        outputs = sess.run(None, feed)
        return dict(zip((o.name for o in sess.get_outputs()), outputs))


@pytest.mark.golden
@pytest.mark.integration_slow
def test_offline_diarization_parity():
    """L4: the offline ONNX speaker probabilities match the HuggingFace reference."""
    from mobius import build

    golden = np.load(_GOLDEN)
    mel = golden["offline_mel"].astype(np.float32)  # (1, T, feat)
    preds_ref = golden["offline_preds"]  # (1, T, num_spks) sigmoid activations

    pkg = build(_MODEL_ID, task="diarization", revision=_REVISION)
    # mobius's DiarizationTask input contract is channel-first [B, feat, T].
    mel_cf = np.transpose(mel, (0, 2, 1))
    out = _run_onnx(pkg, {"input_features": mel_cf})["speaker_probs"]

    assert out.shape == preds_ref.shape
    np.testing.assert_allclose(out, preds_ref, atol=1e-4)


@pytest.mark.generation
@pytest.mark.integration_slow
def test_streaming_diarization_session():
    """L5: a multi-chunk streaming session reproduces HuggingFace exactly.

    Threads the AOSC + FIFO cache state through the real streaming ONNX graph
    across 3 chunks (self-consistently, using only the graph's own outputs as
    the next call's inputs) and checks every chunk's speaker probabilities and
    cache state against the independently-computed HuggingFace reference.
    """
    from mobius import build

    golden = np.load(_GOLDEN)
    meta = json.loads(str(golden["meta"]))
    num_spks = int(meta["num_speakers"])
    num_chunks = int(meta["num_stream_chunks"])
    cache_capacity = int(meta["streaming_speaker_cache_length"])
    fifo_capacity = int(meta["streaming_fifo_length"])

    pkg = build(_MODEL_ID, task="diarization-streaming", revision=_REVISION)
    hidden_size = pkg.config.hidden_size

    # Fresh-stream initial state: all-zero cache/FIFO buffers, no occupancy.
    past_cache_embeds = np.zeros((1, cache_capacity, hidden_size), dtype=np.float32)
    past_cache_probs = np.zeros((1, cache_capacity, num_spks), dtype=np.float32)
    past_fifo = np.zeros((1, fifo_capacity, hidden_size), dtype=np.float32)
    past_num_cache_frames = np.array(0, dtype=np.int64)
    past_num_fifo_frames = np.array(0, dtype=np.int64)
    past_is_compressed = np.array(False, dtype=np.bool_)

    saw_compression = False
    for i in range(num_chunks):
        mel = golden[f"stream_mel_{i}"].astype(np.float32)
        mel_cf = np.transpose(mel, (0, 2, 1))
        feed = {
            "input_features": mel_cf,
            "num_lookahead_frames": golden[f"stream_lookahead_{i}"],
            "past_cache_embeds": past_cache_embeds,
            "past_cache_probs": past_cache_probs,
            "past_fifo": past_fifo,
            "past_num_cache_frames": past_num_cache_frames,
            "past_num_fifo_frames": past_num_fifo_frames,
            "past_is_compressed": past_is_compressed,
        }
        out = _run_onnx(pkg, feed)

        preds_ref = golden[f"stream_preds_{i}"]
        np.testing.assert_allclose(
            out["speaker_probs"], preds_ref, atol=1e-4, err_msg=f"chunk {i} speaker_probs"
        )

        num_cache = int(out["present_num_cache_frames"])
        num_fifo = int(out["present_num_fifo_frames"])
        is_compressed = bool(out["present_is_compressed"])
        assert num_cache == int(golden[f"stream_num_cache_frames_{i}"])
        assert num_fifo == int(golden[f"stream_num_fifo_frames_{i}"])
        assert is_compressed == bool(golden[f"stream_is_compressed_{i}"])
        saw_compression = saw_compression or is_compressed

        np.testing.assert_allclose(
            out["present_cache_embeds"][:, :num_cache],
            golden[f"stream_cache_embeds_{i}"][:, :num_cache],
            atol=1e-3,
            err_msg=f"chunk {i} cache_embeds",
        )
        np.testing.assert_allclose(
            out["present_cache_probs"][:, :num_cache],
            golden[f"stream_cache_probs_{i}"][:, :num_cache],
            atol=1e-4,
            err_msg=f"chunk {i} cache_probs",
        )
        np.testing.assert_allclose(
            out["present_fifo"][:, :num_fifo],
            golden[f"stream_fifo_{i}"][:, :num_fifo],
            atol=1e-3,
            err_msg=f"chunk {i} fifo",
        )

        # Feed this step's own outputs back in as the next call's cache state
        # (self-consistent chaining through the real exported graph).
        past_cache_embeds = out["present_cache_embeds"]
        past_cache_probs = out["present_cache_probs"]
        past_fifo = out["present_fifo"]
        past_num_cache_frames = out["present_num_cache_frames"]
        past_num_fifo_frames = out["present_num_fifo_frames"]
        past_is_compressed = out["present_is_compressed"]

    # The chosen chunk/cache sizes are expected to force at least one AOSC
    # compression event; fail loudly if a future config/golden change stops
    # exercising that path so this test doesn't silently lose coverage.
    assert saw_compression, "expected the streaming session to trigger AOSC compression"
