# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Reusable ONNX generation-policy components."""

from __future__ import annotations

from mobius.generation._policy_components import (
    PolicyCapabilities,
    PolicyComponent,
    attach_policy_components,
    build_adaptive_k_policy,
    build_batch_minimum,
    build_boolean_not,
    build_code_frame_update,
    build_code_history_append,
    build_codec_layout_transpose,
    build_decoder_state_initializer,
    build_decoder_step_update,
    build_effectful_identity,
    build_empty_features,
    build_eos_termination,
    build_euler_model_input,
    build_euler_solver_step,
    build_grammar_logits_processor,
    build_greedy_sampler,
    build_integer_add,
    build_integer_minimum,
    build_integer_row_broadcast,
    build_iteration_cast,
    build_last_token_logits,
    build_masked_token_update,
    build_model_token_cast,
    build_proposal_metrics,
    build_schedule_constant,
    build_schedule_lookup,
    build_seeded_categorical_sampler,
    build_selective_integer_add,
    build_sequence_length,
    build_speculative_acceptance,
    build_speculative_state_rollback,
    build_termination_batch_initializer,
    build_token_block_identity,
    build_token_state_update,
    build_token_to_slot,
    build_tts_decoder_state_initializer,
    build_tts_decoder_step_update,
    build_tts_state_initializer,
)

__all__ = [
    "PolicyCapabilities",
    "PolicyComponent",
    "attach_policy_components",
    "build_adaptive_k_policy",
    "build_batch_minimum",
    "build_boolean_not",
    "build_code_frame_update",
    "build_code_history_append",
    "build_codec_layout_transpose",
    "build_decoder_state_initializer",
    "build_decoder_step_update",
    "build_effectful_identity",
    "build_empty_features",
    "build_eos_termination",
    "build_euler_model_input",
    "build_euler_solver_step",
    "build_grammar_logits_processor",
    "build_greedy_sampler",
    "build_integer_add",
    "build_integer_row_broadcast",
    "build_selective_integer_add",
    "build_integer_minimum",
    "build_iteration_cast",
    "build_last_token_logits",
    "build_masked_token_update",
    "build_model_token_cast",
    "build_proposal_metrics",
    "build_schedule_constant",
    "build_schedule_lookup",
    "build_seeded_categorical_sampler",
    "build_sequence_length",
    "build_speculative_acceptance",
    "build_speculative_state_rollback",
    "build_token_block_identity",
    "build_token_state_update",
    "build_token_to_slot",
    "build_termination_batch_initializer",
    "build_tts_decoder_state_initializer",
    "build_tts_decoder_step_update",
    "build_tts_state_initializer",
]
